# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=1.0.0
maven_group=com.lunazstudios
archives_name=VirtualLoot-Extended
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.1
# Dependencies
architectury_api_version=13.0.8
fabric_loader_version=0.19.3
fabric_api_version=0.116.12+1.21.1
fabric_language_kotlin_version=1.13.6+kotlin.2.2.20
kotlin_for_forge_version=5.10.0
kotlin_for_forge_kotlin_version=2.2.20
kotlin_for_forge_coroutines_version=1.10.2
kotlin_for_forge_serialization_version=1.9.0
cloth_config_version=15.0.140
neoforge_version=21.1.234
cobblemon_version=1.7.3+1.21.1
cobblemon_version_range=>=1.7.3 <1.7.4
cobblemon_neoforge_version_range=[1.7.3,1.7.4)
cobbleworkers_version=2.0.4+1.7.0
cobbleworkers_fabric_maven_version=bbTUCGY1
cobbleworkers_neoforge_maven_version=HEhFpSDA
cobbleworkers_version_range=>=2.0.4
cobbleworkers_neoforge_version_range=[2.0.4,)
cobbreeding_version=2.2.1
cobbreeding_fabric_maven_version=MvTDHePw
cobbreeding_neoforge_maven_version=xt8IiPEN
cobbreeding_version_range=>=2.2.1
cobbreeding_neoforge_version_range=[2.2.1,)
